# Generated by Django 4.2.7 on 2025-11-07 05:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('root', 'Root'), ('admin', 'Admin'), ('user1', 'User1')], default='user1', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('success_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_messages', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='core_upload_user_id_fb53b9_idx'), models.Index(fields=['uploaded_at'], name='core_upload_uploade_135574_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_no', models.CharField(max_length=50, verbose_name='Employee Number')),
                ('ep_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('overstay', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PH', 'Public Holiday'), ('-0.5', 'Half Day'), ('-1', 'Full Day Leave')], max_length=10)),
                ('in_time', models.TimeField(blank=True, null=True, verbose_name='IN')),
                ('out_time', models.TimeField(blank=True, null=True, verbose_name='OUT')),
                ('in_time_2', models.TimeField(blank=True, null=True, verbose_name='IN (2)')),
                ('out_time_2', models.TimeField(blank=True, null=True, verbose_name='OUT (2)')),
                ('in_time_3', models.TimeField(blank=True, null=True, verbose_name='IN (3)')),
                ('out_time_3', models.TimeField(blank=True, null=True, verbose_name='OUT (3)')),
                ('overtime', models.TimeField(blank=True, null=True, verbose_name='OVERTIME')),
                ('overtime_to_mandays', models.TimeField(blank=True, null=True, verbose_name='OVERTIME TO MANDAYS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.company')),
            ],
            options={
                'ordering': ['-date', 'ep_no'],
                'indexes': [models.Index(fields=['ep_no', 'date'], name='core_attend_ep_no_a1b790_idx'), models.Index(fields=['company', 'date'], name='core_attend_company_9ff689_idx'), models.Index(fields=['date'], name='core_attend_date_4e3795_idx')],
                'unique_together': {('ep_no', 'date')},
            },
        ),
    ]
