# Generated by Django 4.2.7 on 2025-11-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Access From Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Access To Date'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PH', 'Public Holiday'), ('WO', 'Week Off'), ('-0.5', 'Half Day'), ('-1', 'Full Day Leave')], max_length=10),
        ),
    ]
