# Generated by Django 4.2.7 on 2025-11-25 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_assigned_date_from_user_assigned_date_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('backup_full', 'Full Backup'), ('backup_incremental', 'Incremental Backup'), ('restore', 'Restore')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies_count', models.IntegerField(default=0)),
                ('records_count', models.IntegerField(default=0)),
                ('records_added', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_backup_user_id_c45508_idx'), models.Index(fields=['created_at'], name='core_backup_created_e5965c_idx')],
            },
        ),
    ]
