# Generated by Django 4.2.7 on 2025-11-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backuplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_no', models.CharField(max_length=50, verbose_name='Employee Number')),
                ('ep_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('access_from', models.DateField(blank=True, help_text='Leave blank for permanent access', null=True, verbose_name='Access From Date')),
                ('access_to', models.DateField(blank=True, help_text='Leave blank for permanent access', null=True, verbose_name='Access To Date')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('request', 'Access Request'), ('admin', 'Admin Assigned')], default='admin', help_text='How this assignment was created', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='core.company')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'user1'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_employ_user_id_de0919_idx'), models.Index(fields=['ep_no', 'is_active'], name='core_employ_ep_no_ffe056_idx'), models.Index(fields=['company', 'is_active'], name='core_employ_company_71004e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('request_created', 'Request Created'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_cancelled', 'Request Cancelled'), ('assignment_created', 'Assignment Created'), ('assignment_removed', 'Assignment Removed'), ('assignment_expired', 'Assignment Expired')], max_length=30)),
                ('target_ep_no', models.CharField(blank=True, max_length=50, verbose_name='Employee Number')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User1 affected by this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_access_timesta_24f204_idx'), models.Index(fields=['actor', 'timestamp'], name='core_access_actor_i_78e464_idx'), models.Index(fields=['target_user', 'timestamp'], name='core_access_target__a0aebf_idx'), models.Index(fields=['target_ep_no', 'timestamp'], name='core_access_target__00c54a_idx'), models.Index(fields=['action', 'timestamp'], name='core_access_action_8715b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_no', models.CharField(max_length=50, verbose_name='Employee Number')),
                ('access_type', models.CharField(choices=[('date_range', 'Date Range'), ('permanent', 'Permanent')], default='date_range', max_length=20)),
                ('access_from', models.DateField(blank=True, null=True, verbose_name='Access From Date')),
                ('access_to', models.DateField(blank=True, null=True, verbose_name='Access To Date')),
                ('justification', models.TextField(help_text='Reason for requesting access')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='core.company')),
                ('requester', models.ForeignKey(limit_choices_to={'role': 'user1'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'status'], name='core_access_request_8d36b4_idx'), models.Index(fields=['status', 'created_at'], name='core_access_status_5c810f_idx'), models.Index(fields=['ep_no', 'status'], name='core_access_ep_no_6e0a8b_idx')],
            },
        ),
    ]
