# Generated by Django 4.2.7 on 2025-12-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employeeassignment_accessrequestauditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandayUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('success_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_messages', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manday_upload_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manday Upload Log',
                'verbose_name_plural': 'Manday Upload Logs',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='core_manday_user_id_f4704e_idx'), models.Index(fields=['uploaded_at'], name='core_manday_uploade_791134_idx')],
            },
        ),
        migrations.CreateModel(
            name='MandaySummaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_no', models.CharField(max_length=50, verbose_name='Employee Number')),
                ('punch_date', models.DateField(verbose_name='Punch Date')),
                ('mandays', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mandays')),
                ('regular_manday_hr', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Regular Manday Hours')),
                ('ot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Overtime')),
                ('trade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trade')),
                ('skill', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill')),
                ('contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract')),
                ('plant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plant')),
                ('plant_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plant Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manday_records', to='core.company')),
            ],
            options={
                'verbose_name': 'Manday Summary Record',
                'verbose_name_plural': 'Manday Summary Records',
                'ordering': ['-punch_date', 'ep_no'],
                'indexes': [models.Index(fields=['ep_no', 'punch_date'], name='core_manday_ep_no_499434_idx'), models.Index(fields=['company', 'punch_date'], name='core_manday_company_8f38ec_idx'), models.Index(fields=['punch_date'], name='core_manday_punch_d_cc5907_idx')],
                'unique_together': {('ep_no', 'punch_date')},
            },
        ),
    ]
