# Generated by Django 4.2.7 on 2025-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mandayuploadlog_mandaysummaryrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandaysummaryrecord',
            name='skill',
        ),
        migrations.AlterField(
            model_name='mandaysummaryrecord',
            name='ot',
            field=models.TimeField(verbose_name='Overtime'),
        ),
        migrations.AlterField(
            model_name='mandaysummaryrecord',
            name='regular_manday_hr',
            field=models.TimeField(verbose_name='Regular Manday Hours'),
        ),
    ]
