# Generated by Django 4.2.7 on 2025-12-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_skill_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandaysummaryrecord',
            name='ot',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Overtime'),
        ),
    ]
