# Generated by Django 4.2.7 on 2025-12-03 06:11

from django.db import migrations
from decimal import Decimal


def convert_time_to_decimal(apps, schema_editor):
    """Convert existing time values in ot field to decimal hours"""
    # Use raw SQL to avoid model conversion issues
    db_alias = schema_editor.connection.alias
    
    from django.db import connection
    with connection.cursor() as cursor:
        # Get all records with their current ot values
        cursor.execute("SELECT id, ot FROM core_mandaysummaryrecord")
        rows = cursor.fetchall()
        
        # Convert each time string to decimal
        updates = []
        for row_id, ot_value in rows:
            if ot_value:
                try:
                    # Parse time string (HH:MM:SS or HH:MM)
                    parts = str(ot_value).split(':')
                    if len(parts) >= 2:
                        hours = int(parts[0])
                        minutes = int(parts[1])
                        # Convert to decimal hours
                        decimal_hours = float(hours) + (float(minutes) / 60.0)
                        updates.append((decimal_hours, row_id))
                except (ValueError, IndexError):
                    # If conversion fails, set to 0
                    updates.append((0.0, row_id))
        
        # Perform batch updates
        for decimal_hours, row_id in updates:
            cursor.execute(
                "UPDATE core_mandaysummaryrecord SET ot = %s WHERE id = %s" % (decimal_hours, row_id)
            )


def reverse_conversion(apps, schema_editor):
    """Reverse migration - convert decimal back to time format"""
    # This is a lossy conversion, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_change_ot_to_decimal'),
    ]

    operations = [
        migrations.RunPython(convert_time_to_decimal, reverse_conversion),
    ]
