# Generated by Django 4.2.7 on 2025-12-13 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_convert_ot_time_to_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('contractor_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Contractor Code')),
                ('contractor_name', models.CharField(max_length=255, verbose_name='Contractor Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contractors',
                'ordering': ['contractor_code'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchdate', models.DateField(verbose_name='Punch Date')),
                ('mandays', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mandays')),
                ('regular_manday_hr', models.TimeField(blank=True, null=True, verbose_name='Regular Manday Hours')),
                ('ot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Overtime')),
                ('location_status', models.CharField(blank=True, max_length=50, verbose_name='Location Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Summaries',
                'db_table': 'daily_summary',
                'ordering': ['-punchdate', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ep_no', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Employee Number')),
                ('ep_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('sector_name', models.CharField(blank=True, max_length=100)),
                ('plant_name', models.CharField(blank=True, max_length=100)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('trade_name', models.CharField(blank=True, max_length=100)),
                ('skill', models.CharField(blank=True, max_length=50)),
                ('card_category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.contractor')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['ep_no'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=50, verbose_name='Export Type')),
                ('record_count', models.IntegerField(verbose_name='Record Count')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_type', models.CharField(max_length=50, verbose_name='File Type')),
                ('total_rows', models.IntegerField(verbose_name='Total Rows')),
                ('imported_rows', models.IntegerField(verbose_name='Imported Rows')),
                ('duplicate_rows', models.IntegerField(verbose_name='Duplicate Rows')),
                ('error_rows', models.IntegerField(verbose_name='Error Rows')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('error_report_path', models.CharField(blank=True, max_length=500, verbose_name='Error Report Path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchdate', models.DateField(verbose_name='Punch Date')),
                ('actual_overstay', models.TimeField(blank=True, null=True, verbose_name='Actual Overstay')),
                ('requested_overtime', models.TimeField(blank=True, null=True, verbose_name='Requested Overtime')),
                ('approved_overtime', models.TimeField(blank=True, null=True, verbose_name='Approved Overtime')),
                ('requested_regular_hours', models.TimeField(blank=True, null=True, verbose_name='Requested Regular Hours')),
                ('approved_regular_hours', models.TimeField(blank=True, null=True, verbose_name='Approved Regular Hours')),
                ('contractor_request_date', models.DateTimeField(blank=True, null=True, verbose_name='Contractor Request Date')),
                ('contractor_remarks', models.TextField(blank=True, verbose_name='Contractor Remarks')),
                ('contractor_reason', models.TextField(blank=True, verbose_name='Contractor Reason')),
                ('actual_eic_code', models.IntegerField(blank=True, null=True, verbose_name='Actual EIC Code')),
                ('requested_eic_code', models.IntegerField(blank=True, null=True, verbose_name='Requested EIC Code')),
                ('eic_approve_date', models.DateTimeField(blank=True, null=True, verbose_name='EIC Approve Date')),
                ('eic_remarks', models.TextField(blank=True, verbose_name='EIC Remarks')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='core.employee')),
            ],
            options={
                'db_table': 'overtime_requests',
                'ordering': ['-punchdate', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='PartialDayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchdate', models.DateField(verbose_name='Punch Date')),
                ('actual_pd_hours', models.TimeField(blank=True, null=True, verbose_name='Actual PD Hours')),
                ('requested_pd_hours', models.TimeField(blank=True, null=True, verbose_name='Requested PD Hours')),
                ('approved_pd_hours', models.TimeField(blank=True, null=True, verbose_name='Approved PD Hours')),
                ('manday_conversion', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Manday Conversion')),
                ('contractor_request_date', models.DateTimeField(blank=True, null=True, verbose_name='Contractor Request Date')),
                ('contractor_remarks', models.TextField(blank=True, verbose_name='Contractor Remarks')),
                ('eic_code', models.IntegerField(blank=True, null=True, verbose_name='EIC Code')),
                ('eic_approve_date', models.DateTimeField(blank=True, null=True, verbose_name='EIC Approve Date')),
                ('eic_remarks', models.TextField(blank=True, verbose_name='EIC Remarks')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_day_requests', to='core.employee')),
            ],
            options={
                'db_table': 'partial_day_requests',
                'ordering': ['-punchdate', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Plant Code')),
                ('plant_name', models.CharField(max_length=255, verbose_name='Plant Name')),
                ('sector_name', models.CharField(blank=True, max_length=100)),
                ('site_code', models.CharField(blank=True, max_length=50)),
                ('site_desc', models.CharField(blank=True, max_length=255, verbose_name='Site Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plants',
                'ordering': ['plant_code'],
            },
        ),
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchdate', models.DateField(verbose_name='Punch Date')),
                ('shift', models.CharField(blank=True, max_length=50)),
                ('punch1_in', models.TimeField(blank=True, null=True, verbose_name='Punch 1 IN')),
                ('punch2_out', models.TimeField(blank=True, null=True, verbose_name='Punch 2 OUT')),
                ('punch3_in', models.TimeField(blank=True, null=True, verbose_name='Punch 3 IN')),
                ('punch4_out', models.TimeField(blank=True, null=True, verbose_name='Punch 4 OUT')),
                ('punch5_in', models.TimeField(blank=True, null=True, verbose_name='Punch 5 IN')),
                ('punch6_out', models.TimeField(blank=True, null=True, verbose_name='Punch 6 OUT')),
                ('early_in', models.TimeField(blank=True, null=True, verbose_name='Early IN')),
                ('late_come', models.TimeField(blank=True, null=True, verbose_name='Late Come')),
                ('early_out', models.TimeField(blank=True, null=True, verbose_name='Early OUT')),
                ('hours_worked', models.TimeField(blank=True, null=True, verbose_name='Hours Worked')),
                ('overstay', models.TimeField(blank=True, null=True, verbose_name='Overstay')),
                ('overtime', models.TimeField(blank=True, null=True, verbose_name='Overtime')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('regular_hours', models.TimeField(blank=True, null=True, verbose_name='Regular Hours')),
                ('manual_request', models.BooleanField(default=False, verbose_name='Manual Request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_records', to='core.employee')),
            ],
            options={
                'db_table': 'punch_records',
                'ordering': ['-punchdate', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='RegularizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchdate', models.DateField(verbose_name='Punch Date')),
                ('old_punch_in', models.TimeField(blank=True, null=True, verbose_name='Old Punch IN')),
                ('old_punch_out', models.TimeField(blank=True, null=True, verbose_name='Old Punch OUT')),
                ('new_punch_in', models.TimeField(blank=True, null=True, verbose_name='New Punch IN')),
                ('new_punch_out', models.TimeField(blank=True, null=True, verbose_name='New Punch OUT')),
                ('contractor_request_date', models.DateTimeField(blank=True, null=True, verbose_name='Contractor Request Date')),
                ('contractor_remarks', models.TextField(blank=True, verbose_name='Contractor Remarks')),
                ('contractor_reason', models.TextField(blank=True, verbose_name='Contractor Reason')),
                ('eic_code', models.IntegerField(blank=True, null=True, verbose_name='EIC Code')),
                ('eic_approve_date', models.DateTimeField(blank=True, null=True, verbose_name='EIC Approve Date')),
                ('eic_remarks', models.TextField(blank=True, verbose_name='EIC Remarks')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='core.employee')),
            ],
            options={
                'db_table': 'regularization_requests',
                'ordering': ['-punchdate', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='UploadPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50, verbose_name='File Type')),
                ('can_upload', models.BooleanField(default=False, verbose_name='Can Upload')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_upload_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_permissions',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mandayuploadlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='MandaySummaryRecord',
        ),
        migrations.DeleteModel(
            name='MandayUploadLog',
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.employee'),
        ),
        migrations.AddIndex(
            model_name='uploadpermission',
            index=models.Index(fields=['user', 'file_type'], name='upload_perm_user_id_e9caf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uploadpermission',
            unique_together={('user', 'file_type')},
        ),
        migrations.AddIndex(
            model_name='regularizationrequest',
            index=models.Index(fields=['punchdate'], name='regularizat_punchda_323a17_idx'),
        ),
        migrations.AddIndex(
            model_name='regularizationrequest',
            index=models.Index(fields=['employee', 'punchdate'], name='regularizat_employe_ce6758_idx'),
        ),
        migrations.AddIndex(
            model_name='regularizationrequest',
            index=models.Index(fields=['status'], name='regularizat_status_234617_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regularizationrequest',
            unique_together={('employee', 'punchdate')},
        ),
        migrations.AddIndex(
            model_name='punchrecord',
            index=models.Index(fields=['punchdate'], name='punch_recor_punchda_124b92_idx'),
        ),
        migrations.AddIndex(
            model_name='punchrecord',
            index=models.Index(fields=['employee', 'punchdate'], name='punch_recor_employe_bab762_idx'),
        ),
        migrations.AddIndex(
            model_name='punchrecord',
            index=models.Index(fields=['status'], name='punch_recor_status_01c589_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='punchrecord',
            unique_together={('employee', 'punchdate')},
        ),
        migrations.AddIndex(
            model_name='partialdayrequest',
            index=models.Index(fields=['punchdate'], name='partial_day_punchda_7c9836_idx'),
        ),
        migrations.AddIndex(
            model_name='partialdayrequest',
            index=models.Index(fields=['employee', 'punchdate'], name='partial_day_employe_075066_idx'),
        ),
        migrations.AddIndex(
            model_name='partialdayrequest',
            index=models.Index(fields=['status'], name='partial_day_status_abc94f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partialdayrequest',
            unique_together={('employee', 'punchdate')},
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['punchdate'], name='overtime_re_punchda_96541e_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['employee', 'punchdate'], name='overtime_re_employe_a5294e_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['status'], name='overtime_re_status_5452b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='overtimerequest',
            unique_together={('employee', 'punchdate')},
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['user', 'created_at'], name='import_logs_user_id_f79bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['created_at'], name='import_logs_created_182db0_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['file_type'], name='import_logs_file_ty_c4dc04_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['user', 'created_at'], name='export_logs_user_id_69ecc9_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['created_at'], name='export_logs_created_56e6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['contractor'], name='employees_contrac_537c63_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['plant_name'], name='employees_plant_n_6dbbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['sector_name'], name='employees_sector__2b88b1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['punchdate'], name='daily_summa_punchda_cd19eb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['employee', 'punchdate'], name='daily_summa_employe_891f6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('employee', 'punchdate')},
        ),
    ]
