# Generated by Django 4.2.7 on 2025-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contractor_dailysummary_employee_exportlog_importlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PH', 'Public Holiday'), ('PD', 'Partial Day'), ('WO', 'Week Off'), ('-0.5', 'Half Day'), ('-1', 'Full Day Leave')], max_length=10),
        ),
    ]
