# Generated by Django 4.2 on 2025-12-17 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_pd_status_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason/Category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_reasons', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remark_reasons',
                'ordering': ['reason'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_no', models.CharField(max_length=50, verbose_name='EP Number')),
                ('date', models.DateField(verbose_name='Attendance Date')),
                ('remarks_text', models.TextField(verbose_name='Remarks/Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_response', models.TextField(blank=True, verbose_name='Admin Response')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='core.attendancerecord')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remarks', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks', to='core.remarkreason')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='remarkreason',
            index=models.Index(fields=['company', 'is_active'], name='remark_reas_company_66d065_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remarkreason',
            unique_together={('company', 'reason')},
        ),
        migrations.AddIndex(
            model_name='attendanceremark',
            index=models.Index(fields=['ep_no', 'date'], name='attendance__ep_no_006981_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceremark',
            index=models.Index(fields=['created_by', 'created_at'], name='attendance__created_19466b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceremark',
            index=models.Index(fields=['status'], name='attendance__status_eb0abe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceremark',
            index=models.Index(fields=['attendance_record'], name='attendance__attenda_5a449a_idx'),
        ),
    ]
