# Generated by Django 4.2 on 2025-12-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remarkreason_attendanceremark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='hours',
            field=models.CharField(blank=True, max_length=20, verbose_name='HOURS'),
        ),
    ]
