# Generated by Django 4.2 on 2025-12-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_arc_summary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='actual_overstay',
            field=models.CharField(blank=True, max_length=20, verbose_name='Actual Overstay'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='approved_overtime',
            field=models.CharField(blank=True, max_length=20, verbose_name='Approved Overtime'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='approved_regular_manday_hours',
            field=models.CharField(blank=True, max_length=20, verbose_name='Approved Regular Manday Hours'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='contractor_ot_reason',
            field=models.TextField(blank=True, verbose_name='Contractor OT Reason'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='contractor_ot_remarks',
            field=models.TextField(blank=True, verbose_name='Contractor OT Remarks'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='ot_request_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='OT Request Status'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='requested_eic_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Requested EIC Code'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='requested_eic_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Requested EIC Name'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='requested_overtime',
            field=models.CharField(blank=True, max_length=20, verbose_name='Requested Overtime'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='requested_regular_manday_hours',
            field=models.CharField(blank=True, max_length=20, verbose_name='Requested Regular Manday Hours'),
        ),
    ]
